// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hub/pessimist/clientstate.proto

// buf:lint:ignore PACKAGE_VERSION_SUFFIX

package hub

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ClientState struct {
	DependentClientId string `protobuf:"bytes,1,opt,name=dependent_client_id,json=dependentClientId,proto3" json:"dependent_client_id,omitempty"`
	LatestHeight      int64  `protobuf:"fixed64,2,opt,name=latest_height,json=latestHeight,proto3" json:"latest_height,omitempty"`
}

func (m *ClientState) Reset()         { *m = ClientState{} }
func (m *ClientState) String() string { return proto.CompactTextString(m) }
func (*ClientState) ProtoMessage()    {}
func (*ClientState) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff931cc301c21953, []int{0}
}
func (m *ClientState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClientState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClientState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClientState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientState.Merge(m, src)
}
func (m *ClientState) XXX_Size() int {
	return m.Size()
}
func (m *ClientState) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientState.DiscardUnknown(m)
}

var xxx_messageInfo_ClientState proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ClientState)(nil), "hub.pessimist.ClientState")
}

func init() { proto.RegisterFile("hub/pessimist/clientstate.proto", fileDescriptor_ff931cc301c21953) }

var fileDescriptor_ff931cc301c21953 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0x3d, 0x4e, 0xc4, 0x30,
	0x10, 0x85, 0x63, 0x84, 0x90, 0x08, 0xac, 0x04, 0x0b, 0xc5, 0x6a, 0x0b, 0x67, 0x05, 0xcd, 0x56,
	0x19, 0x09, 0x3a, 0x4a, 0x68, 0xd8, 0x76, 0xe9, 0x68, 0xa2, 0xfc, 0x0c, 0xb6, 0xa5, 0x38, 0x13,
	0xc5, 0x13, 0x24, 0x6e, 0x40, 0xc9, 0x11, 0x38, 0x0e, 0xe5, 0x96, 0x94, 0x28, 0xb9, 0x08, 0x8a,
	0x2d, 0xa5, 0x7b, 0x7e, 0xef, 0xf3, 0x9b, 0x99, 0x38, 0xd1, 0x7d, 0x01, 0x2d, 0x3a, 0x67, 0xac,
	0x71, 0x0c, 0x65, 0x6d, 0xb0, 0x61, 0xc7, 0x39, 0x63, 0xda, 0x76, 0xc4, 0xb4, 0x5c, 0xe8, 0xbe,
	0x48, 0x67, 0x60, 0x7d, 0xad, 0x48, 0x91, 0x4f, 0x60, 0x52, 0x01, 0x5a, 0x27, 0x8a, 0x48, 0xd5,
	0x08, 0xfe, 0x55, 0xf4, 0x6f, 0xc0, 0xc6, 0xa2, 0xe3, 0xdc, 0xb6, 0x01, 0xb8, 0xd1, 0xf1, 0xd9,
	0x93, 0xaf, 0x7e, 0x99, 0xaa, 0x97, 0x69, 0x7c, 0x55, 0x61, 0x8b, 0x4d, 0x85, 0x0d, 0x67, 0x61,
	0x66, 0x66, 0xaa, 0x95, 0xd8, 0x88, 0xed, 0xe9, 0xfe, 0x72, 0x8e, 0xc2, 0x97, 0x5d, 0xb5, 0xbc,
	0x8d, 0x17, 0x75, 0xce, 0xe8, 0x38, 0xd3, 0x68, 0x94, 0xe6, 0xd5, 0xd1, 0x46, 0x6c, 0x2f, 0xf6,
	0xe7, 0xc1, 0x7c, 0xf6, 0xde, 0xc3, 0xf1, 0xe7, 0x77, 0x12, 0x3d, 0xee, 0x7e, 0x06, 0x29, 0x0e,
	0x83, 0x14, 0x7f, 0x83, 0x14, 0x5f, 0xa3, 0x8c, 0x0e, 0xa3, 0x8c, 0x7e, 0x47, 0x19, 0xbd, 0x82,
	0x32, 0x3c, 0x1d, 0x53, 0x92, 0x85, 0x92, 0x9c, 0x25, 0x07, 0x1d, 0xd6, 0xf9, 0x07, 0x76, 0xf0,
	0x7e, 0x37, 0xcb, 0x92, 0x2a, 0x2c, 0x1d, 0xe8, 0xbe, 0x28, 0x4e, 0xfc, 0xee, 0xf7, 0xff, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x89, 0x9d, 0x15, 0x92, 0x24, 0x01, 0x00, 0x00,
}

func (m *ClientState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClientState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClientState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LatestHeight != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(m.LatestHeight))
		i--
		dAtA[i] = 0x11
	}
	if len(m.DependentClientId) > 0 {
		i -= len(m.DependentClientId)
		copy(dAtA[i:], m.DependentClientId)
		i = encodeVarintClientstate(dAtA, i, uint64(len(m.DependentClientId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintClientstate(dAtA []byte, offset int, v uint64) int {
	offset -= sovClientstate(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ClientState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DependentClientId)
	if l > 0 {
		n += 1 + l + sovClientstate(uint64(l))
	}
	if m.LatestHeight != 0 {
		n += 9
	}
	return n
}

func sovClientstate(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozClientstate(x uint64) (n int) {
	return sovClientstate(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ClientState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClientstate
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClientState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClientState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DependentClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientstate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClientstate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClientstate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DependentClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestHeight", wireType)
			}
			m.LatestHeight = 0
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			m.LatestHeight = int64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
		default:
			iNdEx = preIndex
			skippy, err := skipClientstate(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClientstate
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipClientstate(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowClientstate
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClientstate
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClientstate
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthClientstate
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupClientstate
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthClientstate
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthClientstate        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowClientstate          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupClientstate = fmt.Errorf("proto: unexpected end of group")
)
